### ISSUE TITLE
Update pre-existing policies with new changes

### ISSUE THREAD

**Issue by skim0119** [raide-project/ctf_public#16]
## Update require:

One change in environment is changing the perspective of red agent. Previously, the policy accounted the fact that red must play in reversed perspective. The environment is changed so that we can apply same policy for both blue and red with same perspective. Some, legacy policies must be updated.

- [x] roomba
- [x] defence
- [x] patrol

**Comment by skim0119** [comment]
7d169a17046719fc64c42982a17aec9a5ba5104d
5b402d7d02bd552956e4f5ff6d825afd5dd19d10

**Comment by skim0119** [comment]
Same adjustment needs to be made to defense policy and patrol policy.

**Comment by daniely3** [comment]
the observation passed to defense policy for red is all -1
